/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticationForgotPasswordRouteImport } from './routes/_authentication/forgot-password'
import { Route as AuthenticationLoginRouteImport } from './routes/_authentication/login'
import { Route as AuthenticationRegisterRouteImport } from './routes/_authentication/register'
import { Route as AuthenticationResetPasswordRouteImport } from './routes/_authentication/reset-password'
import { Route as MiscHealthRouteImport } from './routes/_misc/health'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLuckyRouteImport } from './routes/_public/lucky'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard/categories'
import { Route as AuthenticatedDashboardRecipesRouteImport } from './routes/_authenticated/dashboard/recipes'
import { Route as PublicCategoriesIndexRouteImport } from './routes/_public/categories/index'
import { Route as PublicCategoriesIdRouteImport } from './routes/_public/categories/$id'
import { Route as PublicRecipesIndexRouteImport } from './routes/_public/recipes/index'
import { Route as PublicRecipesIdRouteImport } from './routes/_public/recipes/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories/$id'
import { Route as ApiRecipesIndexRouteImport } from './routes/api/recipes/index'
import { Route as ApiRecipesIdRouteImport } from './routes/api/recipes/$id'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/_authenticated/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationForgotPasswordRoute =
  AuthenticationForgotPasswordRouteImport.update({
    id: '/_authentication/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/_authentication/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRegisterRoute = AuthenticationRegisterRouteImport.update({
  id: '/_authentication/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationResetPasswordRoute =
  AuthenticationResetPasswordRouteImport.update({
    id: '/_authentication/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const MiscHealthRoute = MiscHealthRouteImport.update({
  id: '/_misc/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLuckyRoute = PublicLuckyRouteImport.update({
  id: '/lucky',
  path: '/lucky',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRecipesRoute =
  AuthenticatedDashboardRecipesRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const PublicCategoriesIndexRoute = PublicCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCategoriesIdRoute = PublicCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRecipesIndexRoute = PublicRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRecipesIdRoute = PublicRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/api/categories/$id',
  path: '/api/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIndexRoute = ApiRecipesIndexRouteImport.update({
  id: '/api/recipes/',
  path: '/api/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdRoute = ApiRecipesIdRouteImport.update({
  id: '/api/recipes/$id',
  path: '/api/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/login': typeof AuthenticationLoginRoute
  '/register': typeof AuthenticationRegisterRoute
  '/reset-password': typeof AuthenticationResetPasswordRoute
  '/health': typeof MiscHealthRoute
  '/lucky': typeof PublicLuckyRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/recipes': typeof AuthenticatedDashboardRecipesRoute
  '/categories/$id': typeof PublicCategoriesIdRoute
  '/recipes/$id': typeof PublicRecipesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/categories/': typeof PublicCategoriesIndexRoute
  '/recipes/': typeof PublicRecipesIndexRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/recipes/': typeof ApiRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/login': typeof AuthenticationLoginRoute
  '/register': typeof AuthenticationRegisterRoute
  '/reset-password': typeof AuthenticationResetPasswordRoute
  '/health': typeof MiscHealthRoute
  '/lucky': typeof PublicLuckyRoute
  '/': typeof PublicIndexRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/recipes': typeof AuthenticatedDashboardRecipesRoute
  '/categories/$id': typeof PublicCategoriesIdRoute
  '/recipes/$id': typeof PublicRecipesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/categories': typeof PublicCategoriesIndexRoute
  '/recipes': typeof PublicRecipesIndexRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/recipes': typeof ApiRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authentication/register': typeof AuthenticationRegisterRoute
  '/_authentication/reset-password': typeof AuthenticationResetPasswordRoute
  '/_misc/health': typeof MiscHealthRoute
  '/_public/lucky': typeof PublicLuckyRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/recipes': typeof AuthenticatedDashboardRecipesRoute
  '/_public/categories/$id': typeof PublicCategoriesIdRoute
  '/_public/recipes/$id': typeof PublicRecipesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/categories/': typeof PublicCategoriesIndexRoute
  '/_public/recipes/': typeof PublicRecipesIndexRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/recipes/': typeof ApiRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/health'
    | '/lucky'
    | '/dashboard/categories'
    | '/dashboard/recipes'
    | '/categories/$id'
    | '/recipes/$id'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/recipes/$id'
    | '/dashboard/'
    | '/categories/'
    | '/recipes/'
    | '/api/categories/'
    | '/api/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/health'
    | '/lucky'
    | '/'
    | '/dashboard/categories'
    | '/dashboard/recipes'
    | '/categories/$id'
    | '/recipes/$id'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/recipes/$id'
    | '/dashboard'
    | '/categories'
    | '/recipes'
    | '/api/categories'
    | '/api/recipes'
  id:
    | '__root__'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_authentication/forgot-password'
    | '/_authentication/login'
    | '/_authentication/register'
    | '/_authentication/reset-password'
    | '/_misc/health'
    | '/_public/lucky'
    | '/_public/'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/recipes'
    | '/_public/categories/$id'
    | '/_public/recipes/$id'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/recipes/$id'
    | '/_authenticated/dashboard/'
    | '/_public/categories/'
    | '/_public/recipes/'
    | '/api/categories/'
    | '/api/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticationForgotPasswordRoute: typeof AuthenticationForgotPasswordRoute
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationRegisterRoute: typeof AuthenticationRegisterRoute
  AuthenticationResetPasswordRoute: typeof AuthenticationResetPasswordRoute
  MiscHealthRoute: typeof MiscHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
  ApiRecipesIdRoute: typeof ApiRecipesIdRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiRecipesIndexRoute: typeof ApiRecipesIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/forgot-password': {
      id: '/_authentication/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthenticationForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/register': {
      id: '/_authentication/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticationRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/reset-password': {
      id: '/_authentication/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthenticationResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_misc/health': {
      id: '/_misc/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof MiscHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/lucky': {
      id: '/_public/lucky'
      path: '/lucky'
      fullPath: '/lucky'
      preLoaderRoute: typeof PublicLuckyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/recipes': {
      id: '/_authenticated/dashboard/recipes'
      path: '/recipes'
      fullPath: '/dashboard/recipes'
      preLoaderRoute: typeof AuthenticatedDashboardRecipesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_public/categories/': {
      id: '/_public/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof PublicCategoriesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/categories/$id': {
      id: '/_public/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof PublicCategoriesIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/recipes/': {
      id: '/_public/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof PublicRecipesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/recipes/$id': {
      id: '/_public/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof PublicRecipesIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/api/categories/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/': {
      id: '/api/recipes/'
      path: '/api/recipes'
      fullPath: '/api/recipes/'
      preLoaderRoute: typeof ApiRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id': {
      id: '/api/recipes/$id'
      path: '/api/recipes/$id'
      fullPath: '/api/recipes/$id'
      preLoaderRoute: typeof ApiRecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLuckyRoute: typeof PublicLuckyRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCategoriesIdRoute: typeof PublicCategoriesIdRoute
  PublicRecipesIdRoute: typeof PublicRecipesIdRoute
  PublicCategoriesIndexRoute: typeof PublicCategoriesIndexRoute
  PublicRecipesIndexRoute: typeof PublicRecipesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLuckyRoute: PublicLuckyRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCategoriesIdRoute: PublicCategoriesIdRoute,
  PublicRecipesIdRoute: PublicRecipesIdRoute,
  PublicCategoriesIndexRoute: PublicCategoriesIndexRoute,
  PublicRecipesIndexRoute: PublicRecipesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardRecipesRoute: typeof AuthenticatedDashboardRecipesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardRecipesRoute: AuthenticatedDashboardRecipesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticationForgotPasswordRoute: AuthenticationForgotPasswordRoute,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationRegisterRoute: AuthenticationRegisterRoute,
  AuthenticationResetPasswordRoute: AuthenticationResetPasswordRoute,
  MiscHealthRoute: MiscHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
  ApiRecipesIdRoute: ApiRecipesIdRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiRecipesIndexRoute: ApiRecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
